# Unique name for this workflow
name: Deploy master branch to production org

# Definition when the workflow should run
on:
    push:
      branches: [ master ]
      paths:
        - 'force-app/**'
            

# Jobs to be executed
jobs:
    deploy-branch-to-production-org:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
          
            # Now we install nodejs in the VM, and specify version 14
            - uses: actions/setup-node@v2
              with:
                node-version: '14'

             # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
          
            # Read Apex::[]::Apex To Get Class Names
            - name: 'Read Latest Commit Message'
              env:
                PR_BODY: ${{github.event.head_commit.message}}
              run: |
                  echo $PR_BODY
                  echo $PR_BODY > ./pr_body.txt
                  node ./parsePR.js              
                  TESTS=$(cat testsToRun.txt) 
                  echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
              
            - name: 'Deploy the entire branch to Production org - run specified tests'
              if: ${{ env.APEX_TESTS != 'all' }}
              run: |
                  echo ${{env.APEX_TESTS}}
 

           
           

           